/** Client-safe Agent Teams request, result, and view vocabulary. */

export type {
  AssignSectionInput,
  AssignSectionResult,
  AvatarColorId,
  AvatarMarker,
  AvatarShapeId,
  BotIdentityMutationResult,
  BotPersonaProfile,
  CreateBotInput,
  CreateBotMutationResult,
  CreateBotResult,
  CreateTeamTaskRequest,
  DeleteBotInput,
  DeleteBotResult,
  HostMailboxMessage,
  HostMailboxMessageSource,
  RenameBotInput,
  RenameBotResult,
  SetAvatarInput,
  SetAvatarResult,
  SidebarSectionId,
  TeamMailboxDeliveryState,
  TeamMemberView,
  TeamMessageId,
  TeamTaskAction,
  TeamTaskId,
  TeamTaskMutationResult,
  TeamTaskStatus,
  TeamTaskView,
  TeamView,
  UpdatePersonaInput,
  UpdatePersonaResult,
  UpdateTeamTaskRequest,
} from './types.ts'
